name: 'run my-acions'

on:
  schedule:
    - cron: '50 3 * * *' #中午12:00执行，修改时注意时区
  watch:
    types: started
  #push:
    #branches:
      #- master
  workflow_dispatch:

env:
  REPO_URL: https://github.com/luolongfei/freenom

jobs:
  bili&tieba:
    runs-on: ubuntu-latest
    if: github.repository != 'happy888888/BiliExp' || github.event_name == 'workflow_dispatch'
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v2
      with: 
        repository: ${{ secrets.REPOSITORY }}
        ref: ${{ secrets.REF }}

    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/run_in_Actions/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: 执行BiliExp
      run: bash ./run_in_Actions/run_BiliExp.sh
      env:
          ADVCONFIG: ${{ secrets.ADVCONFIG }}
          BILICONFIG: ${{ secrets.BILICONFIG }}
          PUSH_MESSAGE: ${{ secrets.PUSH_MESSAGE }}
          SIMPLIFIED: 1

    - name: 'Start Sign'
        env:
          BDUSS: ${{ secrets.BDUSS }}
        run: python tieba.py